import {
    Mission,
    MissionStep,
    Vendor,
    VendorQuote,
    Policy,
    ProcurementDocument,
    ApprovalRequest,
    AgentLog,
} from "./agents/types";

// ===== VENDORS =====
export const SEED_VENDORS: Vendor[] = [
    {
        id: "v-001",
        name: "TechDirect Pro",
        website: "https://techdirect.example.com",
        category: "IT Hardware",
        is_whitelisted: true,
        rating: 4.8,
        contact_email: "sales@techdirect.com",
        notes: "Preferred vendor for laptops and monitors",
        created_at: "2025-12-01T10:00:00Z",
    },
    {
        id: "v-002",
        name: "GlobalSupply Co",
        website: "https://globalsupply.example.com",
        category: "IT Hardware",
        is_whitelisted: true,
        rating: 4.5,
        contact_email: "orders@globalsupply.com",
        notes: "Competitive pricing on bulk orders",
        created_at: "2025-11-15T09:00:00Z",
    },
    {
        id: "v-003",
        name: "PrimeOffice Solutions",
        website: "https://primeoffice.example.com",
        category: "Office Supplies",
        is_whitelisted: true,
        rating: 4.2,
        contact_email: "support@primeoffice.com",
        notes: "Fast delivery, good for furniture & supplies",
        created_at: "2025-10-20T14:00:00Z",
    },
    {
        id: "v-004",
        name: "CloudWare Systems",
        website: "https://cloudware.example.com",
        category: "Software",
        is_whitelisted: false,
        rating: 4.6,
        contact_email: "licensing@cloudware.com",
        notes: "SaaS and software licensing",
        created_at: "2025-09-10T11:00:00Z",
    },
    {
        id: "v-005",
        name: "SecureNet Distributors",
        website: "https://securenet.example.com",
        category: "Networking",
        is_whitelisted: true,
        rating: 4.9,
        contact_email: "enterprise@securenet.com",
        notes: "Networking equipment and security hardware",
        created_at: "2025-08-05T08:00:00Z",
    },
    {
        id: "v-006",
        name: "BudgetTech Outlet",
        website: "https://budgettech.example.com",
        category: "IT Hardware",
        is_whitelisted: false,
        rating: 3.2,
        contact_email: "info@budgettech.com",
        notes: "Low prices but inconsistent availability",
        created_at: "2025-07-01T12:00:00Z",
    },
];

// ===== POLICIES =====
export const SEED_POLICIES: Policy[] = [
    {
        id: "p-001",
        name: "Minimum Quotes Required",
        description: "Require minimum number of quotes for purchases above threshold",
        category: "sourcing",
        rule_text: "Minimum 3 quotes required for items exceeding $1,000 per unit",
        threshold_amount: 1000,
        is_active: true,
        created_at: "2025-06-01T10:00:00Z",
    },
    {
        id: "p-002",
        name: "Budget Cap - Single Purchase",
        description: "Maximum spending limit for a single procurement mission",
        category: "budget",
        rule_text: "Total procurement cost must not exceed $50,000 without VP approval",
        threshold_amount: 50000,
        is_active: true,
        created_at: "2025-06-01T10:00:00Z",
    },
    {
        id: "p-003",
        name: "Whitelisted Vendors Only",
        description: "Prefer pre-approved vendors for all purchases",
        category: "vendor",
        rule_text: "Items over $5,000 must be purchased from whitelisted vendors only",
        threshold_amount: 5000,
        is_active: true,
        created_at: "2025-06-01T10:00:00Z",
    },
    {
        id: "p-004",
        name: "Eco-Friendly Preference",
        description: "Prefer environmentally sustainable products",
        category: "sustainability",
        rule_text: "When available, prefer Energy Star certified or eco-friendly alternatives within 10% price premium",
        threshold_amount: null,
        is_active: true,
        created_at: "2025-06-01T10:00:00Z",
    },
    {
        id: "p-005",
        name: "Delivery Timeline",
        description: "Ensure vendor can meet required delivery deadlines",
        category: "logistics",
        rule_text: "Selected vendor shipping time must be within the requested delivery window",
        threshold_amount: null,
        is_active: true,
        created_at: "2025-06-01T10:00:00Z",
    },
];

// ===== SAMPLE MISSIONS =====
export const SEED_MISSIONS: Mission[] = [
    {
        id: "m-001",
        request_text: "We need 50 high-end laptops for the development team by next Friday. Budget is $75,000.",
        status: "completed",
        parsed_items: [
            {
                name: "High-End Developer Laptop",
                quantity: 50,
                category: "IT Hardware",
                specifications: "16GB+ RAM, 512GB SSD, i7/Ryzen 7+",
                estimated_unit_price: 1500,
            },
        ],
        total_budget: 75000,
        total_savings: 8500,
        deadline: "2026-02-21T17:00:00Z",
        result_summary: "Successfully procured 50 Dell Latitude 5550 laptops from TechDirect Pro at $1,330/unit. Total cost: $66,500. Savings: $8,500 vs. budget.",
        created_at: "2026-02-14T09:00:00Z",
        updated_at: "2026-02-14T14:30:00Z",
    },
    {
        id: "m-002",
        request_text: "Purchase 200 ergonomic office chairs for the new floor expansion. Need delivery within 2 weeks.",
        status: "awaiting_approval",
        parsed_items: [
            {
                name: "Ergonomic Office Chair",
                quantity: 200,
                category: "Office Furniture",
                specifications: "Adjustable lumbar, mesh back, armrests",
                estimated_unit_price: 350,
            },
        ],
        total_budget: 70000,
        total_savings: null,
        deadline: "2026-03-02T17:00:00Z",
        result_summary: null,
        created_at: "2026-02-15T11:00:00Z",
        updated_at: "2026-02-15T12:00:00Z",
    },
    {
        id: "m-003",
        request_text: "Get 10 enterprise firewall appliances for the data center upgrade. Top priority security.",
        status: "running",
        parsed_items: [
            {
                name: "Enterprise Firewall Appliance",
                quantity: 10,
                category: "Networking",
                specifications: "Next-gen, IPS/IDS, 10Gbps throughput",
                estimated_unit_price: 4500,
            },
        ],
        total_budget: 50000,
        total_savings: null,
        deadline: "2026-02-28T17:00:00Z",
        result_summary: null,
        created_at: "2026-02-16T08:00:00Z",
        updated_at: "2026-02-16T08:15:00Z",
    },
];

// ===== MISSION STEPS =====
export const SEED_STEPS: MissionStep[] = [
    // Mission 1 steps (completed)
    {
        id: "s-001",
        mission_id: "m-001",
        agent_name: "orchestrator",
        step_order: 1,
        action: "Parse procurement request",
        reasoning: "Extracted: 50 high-end laptops, dev team, deadline next Friday, $75K budget. Category: IT Hardware.",
        result: "Successfully parsed request into structured procurement items",
        status: "completed",
        started_at: "2026-02-14T09:00:05Z",
        completed_at: "2026-02-14T09:00:12Z",
        metadata: {},
    },
    {
        id: "s-002",
        mission_id: "m-001",
        agent_name: "sourcing_scout",
        step_order: 2,
        action: "Search vendors for high-end developer laptops",
        reasoning: "Queried 4 vendors in IT Hardware category. TechDirect Pro offers Dell Latitude 5550 at $1,330/unit (best price). GlobalSupply Co at $1,410. BudgetTech at $1,280 but 3-week shipping delay.",
        result: "Found 4 quotes. Recommended: TechDirect Pro — best balance of price ($1,330), availability (In Stock), and vendor rating (4.8★)",
        status: "completed",
        started_at: "2026-02-14T09:00:12Z",
        completed_at: "2026-02-14T09:01:45Z",
        metadata: { vendors_checked: 4, quotes_received: 4 },
    },
    {
        id: "s-003",
        mission_id: "m-001",
        agent_name: "compliance_officer",
        step_order: 3,
        action: "Verify compliance against procurement policies",
        reasoning: "Checked 5 active policies. All passed: ✅ 3+ quotes obtained, ✅ Total $66,500 within $75K budget, ✅ TechDirect Pro is whitelisted, ✅ Energy Star certified, ✅ 5-day shipping within deadline.",
        result: "All compliance checks passed. Procurement is policy-compliant.",
        status: "completed",
        started_at: "2026-02-14T09:01:45Z",
        completed_at: "2026-02-14T09:02:10Z",
        metadata: { policies_checked: 5, passed: 5, failed: 0 },
    },
    {
        id: "s-004",
        mission_id: "m-001",
        agent_name: "hitl_bridge",
        step_order: 4,
        action: "Request human approval for $66,500 purchase",
        reasoning: "Purchase exceeds $50,000 threshold — VP approval required per policy P-002.",
        result: "Approval granted by VP Engineering (john.smith@company.com)",
        status: "completed",
        started_at: "2026-02-14T09:02:10Z",
        completed_at: "2026-02-14T12:30:00Z",
        metadata: { approver: "john.smith@company.com" },
    },
    {
        id: "s-005",
        mission_id: "m-001",
        agent_name: "document_drafter",
        step_order: 5,
        action: "Generate Purchase Order #PO-2026-0214",
        reasoning: "Creating formal PO document for 50x Dell Latitude 5550 from TechDirect Pro at $1,330/unit.",
        result: "Purchase Order PO-2026-0214 generated successfully",
        status: "completed",
        started_at: "2026-02-14T12:30:00Z",
        completed_at: "2026-02-14T12:31:15Z",
        metadata: { document_type: "purchase_order", po_number: "PO-2026-0214" },
    },
    // Mission 3 steps (running)
    {
        id: "s-010",
        mission_id: "m-003",
        agent_name: "orchestrator",
        step_order: 1,
        action: "Parse procurement request",
        reasoning: "Extracted: 10 enterprise firewall appliances, data center, top priority security, $50K budget.",
        result: "Successfully parsed request",
        status: "completed",
        started_at: "2026-02-16T08:00:05Z",
        completed_at: "2026-02-16T08:00:10Z",
        metadata: {},
    },
    {
        id: "s-011",
        mission_id: "m-003",
        agent_name: "sourcing_scout",
        step_order: 2,
        action: "Search vendors for enterprise firewall appliances",
        reasoning: "Querying networking category vendors. SecureNet Distributors is the primary whitelisted vendor for security hardware...",
        result: null,
        status: "running",
        started_at: "2026-02-16T08:00:10Z",
        completed_at: null,
        metadata: { vendors_checked: 2 },
    },
];

// ===== VENDOR QUOTES =====
export const SEED_QUOTES: VendorQuote[] = [
    {
        id: "q-001",
        mission_id: "m-001",
        vendor_id: "v-001",
        vendor_name: "TechDirect Pro",
        item_name: "Dell Latitude 5550 (i7, 16GB, 512GB)",
        unit_price: 1330,
        quantity: 50,
        total_price: 66500,
        availability: "In Stock",
        shipping_days: 5,
        selected: true,
        reasoning: "Best price-to-performance ratio. Whitelisted vendor with 4.8★ rating. Fast delivery.",
    },
    {
        id: "q-002",
        mission_id: "m-001",
        vendor_id: "v-002",
        vendor_name: "GlobalSupply Co",
        item_name: "Lenovo ThinkPad E16 (i7, 16GB, 512GB)",
        unit_price: 1410,
        quantity: 50,
        total_price: 70500,
        availability: "In Stock",
        shipping_days: 7,
        selected: false,
        reasoning: "Good option but $4,000 more expensive than TechDirect Pro.",
    },
    {
        id: "q-003",
        mission_id: "m-001",
        vendor_id: "v-006",
        vendor_name: "BudgetTech Outlet",
        item_name: "HP ProBook 460 (i7, 16GB, 512GB)",
        unit_price: 1280,
        quantity: 50,
        total_price: 64000,
        availability: "Limited Stock",
        shipping_days: 21,
        selected: false,
        reasoning: "Lowest price but 3-week shipping delay exceeds Friday deadline. Vendor not whitelisted (3.2★).",
    },
    {
        id: "q-004",
        mission_id: "m-001",
        vendor_id: "v-004",
        vendor_name: "CloudWare Systems",
        item_name: "Dell Latitude 5550 (i7, 16GB, 512GB)",
        unit_price: 1475,
        quantity: 50,
        total_price: 73750,
        availability: "In Stock",
        shipping_days: 4,
        selected: false,
        reasoning: "Fast delivery but highest price. Vendor not whitelisted for hardware purchases.",
    },
];

// ===== DOCUMENTS =====
export const SEED_DOCUMENTS: ProcurementDocument[] = [
    {
        id: "d-001",
        mission_id: "m-001",
        type: "rfq",
        title: "RFQ-2026-0214 — Developer Laptops",
        content: `REQUEST FOR QUOTATION\n\nRFQ Number: RFQ-2026-0214\nDate: February 14, 2026\nDeadline for Responses: February 15, 2026\n\nDear Vendor,\n\nWe are soliciting quotations for the following items:\n\nItem: High-End Developer Laptop\nQuantity: 50 units\nSpecifications:\n- Processor: Intel i7 (13th Gen+) or AMD Ryzen 7+\n- RAM: 16GB DDR5 minimum\n- Storage: 512GB NVMe SSD minimum\n- Display: 15.6" FHD IPS\n- OS: Windows 11 Pro\n- Warranty: 3-year on-site\n\nDelivery Requirements:\n- Location: Corporate HQ, Building C\n- Deadline: February 21, 2026\n- Packaging: Individual retail boxes\n\nPlease include unit pricing, bulk discounts, shipping costs, and estimated delivery timeline.\n\nThank you,\nProcurement Department`,
        metadata: { po_number: "RFQ-2026-0214", vendor_count: 4 },
        created_at: "2026-02-14T09:00:15Z",
    },
    {
        id: "d-002",
        mission_id: "m-001",
        type: "purchase_order",
        title: "PO-2026-0214 — 50x Dell Latitude 5550",
        content: `PURCHASE ORDER\n\nPO Number: PO-2026-0214\nDate: February 14, 2026\nVendor: TechDirect Pro\n\nShip To:\nCorporate HQ, Building C\n123 Enterprise Blvd\nSan Francisco, CA 94105\n\nLine Items:\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n1. Dell Latitude 5550\n   - Specs: i7-1365U, 16GB DDR5, 512GB SSD, 15.6" FHD\n   - Qty: 50\n   - Unit Price: $1,330.00\n   - Line Total: $66,500.00\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\nSubtotal: $66,500.00\nShipping: $0.00 (Free shipping on orders >$10K)\nTax: $5,320.00\nTotal: $71,820.00\n\nPayment Terms: Net 30\nDelivery Date: February 19, 2026\n\nApproved By: John Smith, VP Engineering\nDate: February 14, 2026`,
        metadata: { po_number: "PO-2026-0214", total: 71820 },
        created_at: "2026-02-14T12:31:15Z",
    },
    {
        id: "d-003",
        mission_id: "m-001",
        type: "contract_summary",
        title: "Contract Summary — TechDirect Pro Laptop Order",
        content: `CONTRACT SUMMARY\n\nContract Reference: CS-2026-0214\nRelated PO: PO-2026-0214\nDate: February 14, 2026\n\nParties:\n- Buyer: AuraProcure Corp\n- Seller: TechDirect Pro\n\nKey Terms:\n1. Product: 50x Dell Latitude 5550 Developer Laptops\n2. Total Value: $71,820.00 (incl. tax)\n3. Payment: Net 30 from delivery\n4. Warranty: 3-year on-site service by manufacturer\n5. Delivery: By February 19, 2026 to Corp HQ Building C\n6. Returns: 30-day DOA replacement policy\n\nCompliance Notes:\n- ✅ Vendor is on approved whitelist\n- ✅ 4 competitive quotes obtained (policy minimum: 3)\n- ✅ Total within $75K budget authorization\n- ✅ VP approval obtained for purchases >$50K\n- ✅ Energy Star certified product`,
        metadata: { contract_ref: "CS-2026-0214" },
        created_at: "2026-02-14T12:32:00Z",
    },
];

// ===== APPROVAL REQUESTS =====
export const SEED_APPROVALS: ApprovalRequest[] = [
    {
        id: "a-001",
        mission_id: "m-001",
        description: "Approve purchase of 50x Dell Latitude 5550 from TechDirect Pro for $66,500",
        total_amount: 66500,
        status: "approved",
        approver: "john.smith@company.com",
        approved_at: "2026-02-14T12:30:00Z",
        created_at: "2026-02-14T09:02:10Z",
    },
    {
        id: "a-002",
        mission_id: "m-002",
        description: "Approve purchase of 200x Ergonomic Office Chairs — awaiting final vendor selection and compliance review",
        total_amount: 62000,
        status: "pending",
        approver: null,
        approved_at: null,
        created_at: "2026-02-15T12:00:00Z",
    },
];

// ===== AGENT LOGS =====
export const SEED_LOGS: AgentLog[] = [
    {
        id: "l-001",
        mission_id: "m-001",
        agent_name: "orchestrator",
        level: "info",
        message: "Mission initiated: Parsing natural language request",
        payload: { request_text: "We need 50 high-end laptops for the development team by next Friday" },
        created_at: "2026-02-14T09:00:05Z",
    },
    {
        id: "l-002",
        mission_id: "m-001",
        agent_name: "orchestrator",
        level: "info",
        message: "NLP extraction complete — identified 1 procurement item",
        payload: { items: 1, category: "IT Hardware", quantity: 50 },
        created_at: "2026-02-14T09:00:12Z",
    },
    {
        id: "l-003",
        mission_id: "m-001",
        agent_name: "sourcing_scout",
        level: "info",
        message: "Initiating vendor search for: High-End Developer Laptop",
        payload: { category: "IT Hardware", vendors_available: 4 },
        created_at: "2026-02-14T09:00:13Z",
    },
    {
        id: "l-004",
        mission_id: "m-001",
        agent_name: "sourcing_scout",
        level: "debug",
        message: "GET https://api.techdirect.com/v2/products?q=laptop+i7+16gb — 200 OK (342ms)",
        payload: { vendor: "TechDirect Pro", response_time: 342, results: 12 },
        created_at: "2026-02-14T09:00:25Z",
    },
    {
        id: "l-005",
        mission_id: "m-001",
        agent_name: "sourcing_scout",
        level: "warn",
        message: "BudgetTech Outlet: shipping_days=21 exceeds deadline window of 7 days — flagged",
        payload: { vendor: "BudgetTech Outlet", shipping_days: 21, deadline_days: 7 },
        created_at: "2026-02-14T09:01:10Z",
    },
    {
        id: "l-006",
        mission_id: "m-001",
        agent_name: "sourcing_scout",
        level: "info",
        message: "Vendor comparison complete. Recommending TechDirect Pro (best score: 94/100)",
        payload: { scores: { "TechDirect Pro": 94, "GlobalSupply Co": 82, "CloudWare Systems": 71, "BudgetTech Outlet": 45 } },
        created_at: "2026-02-14T09:01:45Z",
    },
    {
        id: "l-007",
        mission_id: "m-001",
        agent_name: "compliance_officer",
        level: "info",
        message: "Running compliance checks against 5 active policies",
        payload: { policies: 5 },
        created_at: "2026-02-14T09:01:46Z",
    },
    {
        id: "l-008",
        mission_id: "m-001",
        agent_name: "compliance_officer",
        level: "info",
        message: "All 5 compliance checks PASSED ✅",
        payload: { passed: 5, failed: 0 },
        created_at: "2026-02-14T09:02:10Z",
    },
    {
        id: "l-009",
        mission_id: "m-001",
        agent_name: "hitl_bridge",
        level: "info",
        message: "Approval request created — pausing workflow for human review",
        payload: { amount: 66500, reason: "Exceeds $50K threshold" },
        created_at: "2026-02-14T09:02:11Z",
    },
    {
        id: "l-010",
        mission_id: "m-001",
        agent_name: "hitl_bridge",
        level: "info",
        message: "✅ Approved by john.smith@company.com — resuming workflow",
        payload: { approver: "john.smith@company.com", wait_time_hours: 3.46 },
        created_at: "2026-02-14T12:30:00Z",
    },
    {
        id: "l-011",
        mission_id: "m-001",
        agent_name: "document_drafter",
        level: "info",
        message: "Generating Purchase Order PO-2026-0214",
        payload: { type: "purchase_order", vendor: "TechDirect Pro" },
        created_at: "2026-02-14T12:30:01Z",
    },
    {
        id: "l-012",
        mission_id: "m-001",
        agent_name: "document_drafter",
        level: "info",
        message: "PO generated and stored in Document Vault",
        payload: { document_id: "d-002", pages: 1 },
        created_at: "2026-02-14T12:31:15Z",
    },
    {
        id: "l-013",
        mission_id: "m-003",
        agent_name: "orchestrator",
        level: "info",
        message: "Mission initiated: 10 enterprise firewall appliances for data center",
        payload: { category: "Networking", priority: "high" },
        created_at: "2026-02-16T08:00:05Z",
    },
    {
        id: "l-014",
        mission_id: "m-003",
        agent_name: "sourcing_scout",
        level: "info",
        message: "Searching networking vendors for enterprise firewall appliances...",
        payload: { vendors_queried: 2, in_progress: true },
        created_at: "2026-02-16T08:00:10Z",
    },
];

// ===== KPI CALCULATIONS =====
export function calculateKPIs(missions: Mission[]) {
    const completed = missions.filter((m) => m.status === "completed");
    const totalSavings = completed.reduce(
        (sum, m) => sum + (m.total_savings || 0),
        0
    );
    const avgCycleTime =
        completed.length > 0
            ? completed.reduce((sum, m) => {
                const start = new Date(m.created_at).getTime();
                const end = new Date(m.updated_at).getTime();
                return sum + (end - start) / 3600000;
            }, 0) / completed.length
            : 0;
    const successRate =
        missions.length > 0
            ? (completed.length / missions.length) * 100
            : 0;
    const activeMissions = missions.filter(
        (m) => m.status === "running" || m.status === "awaiting_approval"
    ).length;

    return {
        totalSavings,
        avgCycleTimeHours: Math.round(avgCycleTime * 10) / 10,
        successRate: Math.round(successRate),
        activeMissions,
        totalMissions: missions.length,
        completedMissions: completed.length,
    };
}
