import { InventoryItem } from "./agents/types";

export const SEED_INVENTORY: InventoryItem[] = [
    {
        id: "inv-001",
        name: "Dell Latitude 5540 Laptop",
        category: "IT Hardware",
        currentStock: 12,
        maxStock: 50,
        threshold: 10,
        unit: "units",
        burnRate: 1.2,
        lastRestocked: "2026-01-15T10:00:00Z",
        status: "healthy",
        daysUntilEmpty: 10,
        autoReorder: true,
    },
    {
        id: "inv-002",
        name: "27\" 4K Monitor (USB-C)",
        category: "IT Hardware",
        currentStock: 4,
        maxStock: 30,
        threshold: 8,
        unit: "units",
        burnRate: 0.8,
        lastRestocked: "2026-01-20T14:30:00Z",
        status: "critical",
        daysUntilEmpty: 5,
        autoReorder: true,
    },
    {
        id: "inv-003",
        name: "Wireless Mouse (Logitech MX)",
        category: "IT Peripherals",
        currentStock: 35,
        maxStock: 100,
        threshold: 20,
        unit: "units",
        burnRate: 2.5,
        lastRestocked: "2026-02-01T09:00:00Z",
        status: "healthy",
        daysUntilEmpty: 14,
        autoReorder: true,
    },
    {
        id: "inv-004",
        name: "A4 Copy Paper (500-sheet)",
        category: "Office Supplies",
        currentStock: 15,
        maxStock: 200,
        threshold: 30,
        unit: "reams",
        burnRate: 5.0,
        lastRestocked: "2026-02-05T11:00:00Z",
        status: "critical",
        daysUntilEmpty: 3,
        autoReorder: true,
    },
    {
        id: "inv-005",
        name: "Ergonomic Office Chair",
        category: "Furniture",
        currentStock: 18,
        maxStock: 40,
        threshold: 8,
        unit: "units",
        burnRate: 0.3,
        lastRestocked: "2026-01-10T08:00:00Z",
        status: "healthy",
        daysUntilEmpty: 60,
        autoReorder: false,
    },
    {
        id: "inv-006",
        name: "USB-C Hub (7-in-1)",
        category: "IT Peripherals",
        currentStock: 6,
        maxStock: 40,
        threshold: 10,
        unit: "units",
        burnRate: 1.0,
        lastRestocked: "2026-01-28T16:00:00Z",
        status: "low",
        daysUntilEmpty: 6,
        autoReorder: true,
    },
    {
        id: "inv-007",
        name: "Toner Cartridge (HP LaserJet)",
        category: "Office Supplies",
        currentStock: 3,
        maxStock: 20,
        threshold: 5,
        unit: "cartridges",
        burnRate: 0.4,
        lastRestocked: "2026-01-22T13:00:00Z",
        status: "critical",
        daysUntilEmpty: 7,
        autoReorder: true,
    },
    {
        id: "inv-008",
        name: "Standing Desk Converter",
        category: "Furniture",
        currentStock: 22,
        maxStock: 30,
        threshold: 5,
        unit: "units",
        burnRate: 0.2,
        lastRestocked: "2026-02-10T10:00:00Z",
        status: "overstock",
        daysUntilEmpty: 110,
        autoReorder: false,
    },
    {
        id: "inv-009",
        name: "Webcam (Logitech C920)",
        category: "IT Peripherals",
        currentStock: 8,
        maxStock: 25,
        threshold: 5,
        unit: "units",
        burnRate: 0.5,
        lastRestocked: "2026-02-08T15:00:00Z",
        status: "healthy",
        daysUntilEmpty: 16,
        autoReorder: true,
    },
    {
        id: "inv-010",
        name: "Microsoft 365 License",
        category: "Software",
        currentStock: 45,
        maxStock: 200,
        threshold: 50,
        unit: "licenses",
        burnRate: 3.0,
        lastRestocked: "2026-02-01T09:00:00Z",
        status: "low",
        daysUntilEmpty: 15,
        autoReorder: true,
    },
    {
        id: "inv-011",
        name: "Cat6 Ethernet Cable (2m)",
        category: "IT Hardware",
        currentStock: 85,
        maxStock: 100,
        threshold: 20,
        unit: "units",
        burnRate: 1.5,
        lastRestocked: "2026-02-12T09:00:00Z",
        status: "healthy",
        daysUntilEmpty: 57,
        autoReorder: false,
    },
    {
        id: "inv-012",
        name: "Whiteboard Markers (Pack of 12)",
        category: "Office Supplies",
        currentStock: 7,
        maxStock: 50,
        threshold: 10,
        unit: "packs",
        burnRate: 0.8,
        lastRestocked: "2026-01-30T12:00:00Z",
        status: "low",
        daysUntilEmpty: 9,
        autoReorder: true,
    },
];
